version: '3.9'

services:
  db:
    image: mysql:8
    container_name: agri-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agri
    ports:
      - "3307:3306"

  backend:
    image: ghcr.io/jordan-programer/agri-backend:latest
    container_name: agri-backend
    ports:
      - "8080:8080"
    depends_on:
      - ai
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.wniwgtzvpdzfqtgiwwen
      SPRING_DATASOURCE_PASSWORD: jordan@123pasca
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_JPA_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  ai:
    image: ghcr.io/jordan-programer/agri-ai:latest
    container_name: agri-ai
    ports:
      - "5000:5000"
