# Configurações para Supabase (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.wniwgtzvpdzfqtgiwwen}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jordan@123pasca}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto correto para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Manter o update para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL da IA (Com suporte a variável de ambiente para o Railway)
ai.service.url=${AI_SERVICE_URL:http://localhost:5001}
# Para permitir upload de fotos dos produtos e comprovativos
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB

# Configuração de porta para o Railway
server.port=${PORT:8080}