# Configurações para Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://wniwgtzvpdzfqtgiwwen.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=jordan@123pasca
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto correto para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Manter o update para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
